# numpy :boock:

In [ ]:
import tensorflow as tf
import numpy as np

In [11]:
numeros = [1, 2, 3, 4]

In [12]:
array = np.array(numeros)

In [13]:
array

array([1, 2, 3, 4])

In [15]:
np.arange(5, 30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(0, 50, 5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [23]:
np.random.randint(0, 100, 5)

array([58, 24, 38, 33, 31])

In [26]:
array = np.random.randint(0, 100, 15)

In [27]:
array

array([28, 35,  2, 76, 29, 42, 88, 99, 94, 35, 90, 96, 82, 95, 60])

In [29]:
array.max()

99

In [30]:
array.argmax()

7

In [31]:
array.min()

2

In [32]:
array.mean()

63.4

In [33]:
array.reshape(5, 3)

array([[28, 35,  2],
       [76, 29, 42],
       [88, 99, 94],
       [35, 90, 96],
       [82, 95, 60]])

In [34]:
array

array([28, 35,  2, 76, 29, 42, 88, 99, 94, 35, 90, 96, 82, 95, 60])

In [36]:
array = array.reshape(5, 3)

In [37]:
array

array([[28, 35,  2],
       [76, 29, 42],
       [88, 99, 94],
       [35, 90, 96],
       [82, 95, 60]])

In [38]:
array[2,2]

94

In [40]:
filtro = array > 30
array_2 = array[filtro]

In [41]:
array_2

array([35, 76, 42, 88, 99, 94, 35, 90, 96, 82, 95, 60])