In [3]:
import tensorflow as tf
import numpy as np

In [6]:
aleatorio_a = np.random.uniform(0, 50, (4, 4))

In [7]:
aleatorio_a

array([[8.50013751e+00, 3.23583772e-02, 3.19730657e+01, 4.45398213e+01],
       [3.15797756e+01, 1.51329192e+01, 8.27120450e+00, 1.63043038e+01],
       [4.73376928e+01, 2.33639995e+01, 9.72809852e+00, 4.82674664e+01],
       [3.19839217e+01, 2.36846957e+01, 2.31942478e+01, 1.81523123e+01]])

In [8]:
aleatorio_b = np.random.uniform(0, 50, (4, 1))

In [10]:
aleatorio_b

array([[16.83299083],
       [19.17445027],
       [40.1871203 ],
       [45.39604492]])

In [12]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [15]:
suma = a + b
mul = a * b

In [19]:
with tf.Session() as session:
    resultado = session.run(suma, feed_dict={a:12, b:56})
    print(resultado)

68.0


In [20]:
with tf.Session() as session:
    resultado = session.run(suma, feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado)

[[25.333128 16.865349 48.806057 61.37281 ]
 [50.754227 34.30737  27.445656 35.478752]
 [87.52481  63.551117 49.91522  88.45459 ]
 [77.37997  69.08074  68.590294 63.54836 ]]


In [22]:
with tf.Session() as session:
    resultado_m = session.run(mul, feed_dict={a:12, b:56})
    print(resultado_m)

672.0


In [23]:
with tf.Session() as session:
    resultado_m = session.run(mul, feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_m)

[[1.4308273e+02 5.4468828e-01 5.3820233e+02 7.4973840e+02]
 [6.0552484e+02 2.9016541e+02 1.5859581e+02 3.1262607e+02]
 [1.9023655e+03 9.3893182e+02 3.9094427e+02 1.9397305e+03]
 [1.4519435e+03 1.0751915e+03 1.0529271e+03 8.2404321e+02]]


### Red neuronal

In [24]:
caracteristicas = 10
neuronas = 4

In [25]:
x = tf.placeholder(tf.float32, (None, caracteristicas))

In [27]:
w = tf.Variable(tf.random_normal([caracteristicas, neuronas]))

In [28]:
b = tf.Variable(tf.ones([neuronas]))

In [29]:
mult = tf.matmul(x, w)

In [32]:
z = tf.add(mult, b)

In [33]:
activacion = tf.sigmoid(z)

In [34]:
inicializacion = tf.global_variables_initializer()

In [35]:
valores_x = np.random.random([1, caracteristicas])

In [36]:
valores_x

array([[0.38032325, 0.9921001 , 0.14659067, 0.44047192, 0.34602157,
        0.79097799, 0.67099701, 0.88557695, 0.50372255, 0.45716259]])

In [38]:
with tf.Session() as session:
    session.run(inicializacion)
    resultado = session.run(activacion, feed_dict={x:valores_x})

In [39]:
print(resultado)

[[0.7327169 0.727549  0.9911642 0.3780237]]
