### Regresion con tensorflow

In [2]:
import pandas as pd
import tensorflow as tf

In [3]:
casas = pd.read_csv('precio_casas.csv')

In [4]:
casas.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [9]:
casas_x = casas.drop('median_house_value', axis=1)

In [11]:
casas_x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  
0      1015.0       472.0         1.4936  
1      1129.0       463.0         1.8200  
2       333.0       117.0         1.6509  
3       515.0       226.0         3.1917  
4       624.0       262.0         1.9250

In [12]:
casas_y = casas['median_house_value']

In [20]:
casas_y.head()

0    66900.0
1    80100.0
2    85700.0
3    73400.0
4    65500.0
Name: median_house_value, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(casas_x, casas_y, test_size=0.30)

In [24]:
x_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2565     -117.65     34.08                38.0       2750.0           572.0   
6647     -118.28     33.79                36.0       1989.0           458.0   
9582     -119.35     36.20                31.0       1783.0           382.0   
14689    -122.18     37.74                42.0        541.0           154.0   
7757     -118.38     33.83                40.0       3070.0           570.0   

       population  households  median_income  
2565       1410.0       483.0         3.3836  
6647       1668.0       455.0         3.3009  
9582       1266.0       358.0         2.2264  
14689       380.0       123.0         2.3456  
7757       1264.0       506.0         5.1626

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
normalizador = MinMaxScaler()

In [28]:
normalizador.fit(x_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [29]:
x_train = pd.DataFrame(data=normalizador.transform(x_train), columns=x_train.columns, index=x_train.index)

In [31]:
x_test = pd.DataFrame(data=normalizador.transform(x_test), columns=x_test.columns, index=x_test.index)

In [33]:
x_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1854   0.705179  0.048884            0.686275     0.063899        0.070154   
998    0.722112  0.158342            0.450980     0.109187        0.127891   
5685   0.614542  0.131775            1.000000     0.031053        0.058824   
7566   0.596614  0.138151            0.666667     0.041518        0.042992   
1696   0.708167  0.021254            0.862745     0.045235        0.045165   

      population  households  median_income  
1854    0.030244    0.068750       0.320851  
998     0.059452    0.126645       0.139122  
5685    0.029151    0.054276       0.073130  
7566    0.020658    0.044737       0.363133  
1696    0.021051    0.053783       0.244831

In [34]:
casas.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [37]:
longitude = tf.feature_column.numeric_column('longitude')
latitude = tf.feature_column.numeric_column('latitude')
housing_median_age = tf.feature_column.numeric_column('housing_median_age')
total_rooms = tf.feature_column.numeric_column('total_rooms')
total_bedrooms = tf.feature_column.numeric_column('total_bedrooms')
population = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
median_income = tf.feature_column.numeric_column('median_income')

In [38]:
columnas = [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income]

In [39]:
funcion_entrada = tf.estimator.inputs.pandas_input_fn(x=x_train, y=y_train, batch_size=10, num_epochs=1000, shuffle=True)

In [40]:
modelo = tf.estimator.DNNRegressor(hidden_units=[10, 10, 10], feature_columns=columnas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_log_step_count_steps': 100, '_master': '', '_is_chief': True, '_train_distribute': None, '_service': None, '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_every_n_hours': 10000, '_save_checkpoints_steps': None, '_device_fn': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f49783febe0>, '_tf_random_seed': None, '_session_config': None, '_num_worker_replicas': 1, '_keep_checkpoint_max': 5, '_model_dir': '/tmp/tmp53bthsil', '_task_id': 0, '_task_type': 'worker', '_save_summary_steps': 100, '_evaluation_master': '', '_global_id_in_cluster': 0}


In [41]:
modelo.train(input_fn=funcion_entrada, steps=8000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmp53bthsil/model.ckpt.
INFO:tensorflow:loss = 458388000000.0, step = 1
INFO:tensorflow:global_step/sec: 142.078
INFO:tensorflow:loss = 1042563900000.0, step = 101 (0.708 sec)
INFO:tensorflow:global_step/sec: 182.511
INFO:tensorflow:loss = 272685760000.0, step = 201 (0.555 sec)
INFO:tensorflow:global_step/sec: 219.971
INFO:tensorflow:loss = 449045460000.0, step = 301 (0.446 sec)
INFO:tensorflow:global_step/sec: 191.243
INFO:tensorflow:loss = 188853300000.0, step = 401 (0.523 sec)
INFO:tensorflow:global_step/sec: 196.967
INFO:tensorflow:loss = 177818930000.0, step = 501 (0.529 sec)
INFO:tensorflow:global_step/sec: 193.071
INFO:tensorflow:loss = 126898954000.0, step = 601 (0.507 sec)
INFO:tensorflow:globa

INFO:tensorflow:global_step/sec: 248.273
INFO:tensorflow:loss = 208122560000.0, step = 7701 (0.403 sec)
INFO:tensorflow:global_step/sec: 192.028
INFO:tensorflow:loss = 136768930000.0, step = 7801 (0.520 sec)
INFO:tensorflow:global_step/sec: 149.355
INFO:tensorflow:loss = 199791250000.0, step = 7901 (0.670 sec)
INFO:tensorflow:Saving checkpoints for 8000 into /tmp/tmp53bthsil/model.ckpt.
INFO:tensorflow:Loss for final step: 73052170000.0.


In [49]:
fc_prediccion = tf.estimator.inputs.pandas_input_fn(
    x=x_test, batch_size=10, num_epochs=1,
    shuffle=False)

In [50]:
generador_pred = modelo.predict(fc_prediccion)

In [51]:
predicciones = list(generador_pred)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmp53bthsil/model.ckpt-8000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [52]:
predicciones

[{'predictions': array([239796.56], dtype=float32)},
 {'predictions': array([209526.62], dtype=float32)},
 {'predictions': array([216587.1], dtype=float32)},
 {'predictions': array([236053.19], dtype=float32)},
 {'predictions': array([235776.28], dtype=float32)},
 {'predictions': array([193231.52], dtype=float32)},
 {'predictions': array([236190.16], dtype=float32)},
 {'predictions': array([203317.5], dtype=float32)},
 {'predictions': array([228956.02], dtype=float32)},
 {'predictions': array([240556.89], dtype=float32)},
 {'predictions': array([177534.77], dtype=float32)},
 {'predictions': array([207796.98], dtype=float32)},
 {'predictions': array([202233.08], dtype=float32)},
 {'predictions': array([194400.28], dtype=float32)},
 {'predictions': array([186154.8], dtype=float32)},
 {'predictions': array([272142.9], dtype=float32)},
 {'predictions': array([197122.11], dtype=float32)},
 {'predictions': array([184391.97], dtype=float32)},
 {'predictions': array([183772.16], dtype=float32)

In [53]:
predicciones_finales = []
for prediccion in predicciones:
    predicciones_finales.append(prediccion['predictions'])

In [54]:
predicciones_finales

[array([239796.56], dtype=float32),
 array([209526.62], dtype=float32),
 array([216587.1], dtype=float32),
 array([236053.19], dtype=float32),
 array([235776.28], dtype=float32),
 array([193231.52], dtype=float32),
 array([236190.16], dtype=float32),
 array([203317.5], dtype=float32),
 array([228956.02], dtype=float32),
 array([240556.89], dtype=float32),
 array([177534.77], dtype=float32),
 array([207796.98], dtype=float32),
 array([202233.08], dtype=float32),
 array([194400.28], dtype=float32),
 array([186154.8], dtype=float32),
 array([272142.9], dtype=float32),
 array([197122.11], dtype=float32),
 array([184391.97], dtype=float32),
 array([183772.16], dtype=float32),
 array([175964.53], dtype=float32),
 array([223902.9], dtype=float32),
 array([224499.75], dtype=float32),
 array([246062.3], dtype=float32),
 array([224804.03], dtype=float32),
 array([208528.38], dtype=float32),
 array([203167.72], dtype=float32),
 array([202171.27], dtype=float32),
 array([150663.98], dtype=float32)

In [56]:
from sklearn.metrics import mean_squared_error

In [57]:
mean_squared_error(y_test, predicciones_finales)**0.5

101940.48198357748