## Tensorflow

In [1]:
import tensorflow as tf

In [6]:
cadena_1 = tf.constant("hola")
cadena_2 = tf.constant(" mundo")

In [3]:
print(cadena_1)

Tensor("Const:0", shape=(), dtype=string)


In [4]:
type(cadena_1)

tensorflow.python.framework.ops.Tensor

In [7]:
with tf.Session() as sesion:
    resultado = sesion.run(cadena_1 + cadena_2)

In [8]:
resultado

b'hola mundo'

In [9]:
a = tf.constant(10)
b = tf.constant(5)

In [10]:
with tf.Session() as sesion:
    resultado_i = sesion.run(a + b)

In [11]:
resultado_i

15

In [20]:
Constante = tf.constant(12)
matriz1 = tf.fill((3, 3), 10)
matriz2 = tf.random_normal((5, 5))
matriz3 = tf.random_uniform((4,4), minval=0, maxval=4)
matriz_0 = tf.zeros((3,3))

In [21]:
operaciones = [Constante, matriz1, matriz2, matriz3, matriz_0]

with tf.Session() as sesion:
    for item in operaciones:
        print(sesion.run(item))
        print()

12

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[ 1.2443155  -1.4932038  -0.28038552 -0.8295512  -0.94030267]
 [-0.5458645   0.7409304   1.2283615   0.17460881  0.2479294 ]
 [-0.6669265  -0.4172928  -0.2862146  -2.046548   -0.78578734]
 [ 0.7248212  -1.2662454   0.01599534 -0.39946434 -1.2090108 ]
 [ 0.6951895  -0.5591255  -0.11593967  0.4029455  -1.0082918 ]]

[[2.634996  2.2557607 2.9256105 2.2658515]
 [2.1077013 1.264214  2.1527371 1.0412474]
 [0.6419978 2.2989554 0.2856264 1.1477938]
 [1.7610941 1.0247583 2.647459  2.4096422]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

